USE BDarea52
GO

exec cadAdm		'Felipe', 'felipe@felipe', 'asdasd' 
exec cadAdm		'Alisson', 'alisson@alisson', 'asdasd'
exec cadAdm		'Joao', 'joao@joao', 'asdasd'
exec cadAdm		'Gustavo', 'gustavo@gustavo', 'asdasd'

exec cadJogo	'Counter-Strike Global Offensive', 'FPS', '/img/imgjogo/csgo.png', 1
exec cadJogo	'Dota 2', 'MOBA', '/img/imgjogo/dota2.png', 1
exec cadJogo	'FIFA 17', 'Simulador de Futebol', '/img/imgjogo/fifa17.png', 1
exec cadJogo	'Hearthstone', 'Estratégia com Cards', '/img/imgjogo/heart.png', 1
exec cadJogo	'Heroes of The Storm', 'MOBA', '/img/imgjogo/hots.png', 1
exec cadJogo	'League of Legends', ' MOBA', '/img/imgjogo/lol.png', 1
exec cadJogo	'Overwatch', 'FPS', '/img/imgjogo/overwatch.png', 1

exec cadUser		'Sergio', 'tomatinho@tomatinho', 'asdasd', 'Tomatinho', '01-01-1951'
exec editInfo_User	5, 'Sergio', 'Tomatinho', 1, '01-01-1951', 'Tomatinho'
UPDATE usuarios SET imagem = '/img/img-feed/tomat.png' WHERE 5 = pessoa_id
exec cadUser		'Iaron', 'goldmedal@goldmedal', 'asdasd', 'FakeGoldenMedal', '01-01-1980'
exec editInfo_User	6, 'Iaron', 'FakeGoldenMedal', 1, '01-01-1980', 'Torre sentinela' 
UPDATE usuarios SET imagem = '/img/img-feed/gold.jpg' WHERE 6 = pessoa_id
exec cadUser		'Verners', 'vau@vau', 'asdasd', 'Vau', '01-01-1997'
exec cadUser		'Mario', 'mario@mario', 'asdasd', 'BigFire', '01-01-1995'
exec editInfo_User	8, 'Mario', 'BigFire', 1, '01-01-1995', 'Carne, rimas e boys'
UPDATE usuarios SET imagem = '/img/img-feed/fire.png' WHERE 8 = pessoa_id
exec cadUser		'Victor', 'victor@victor', 'asdasd', 'GLS', '01-01-1998'
exec cadUser		'MacGyver', 'masc@masc', 'asdasd', 'Mascherano', '01-01-1997'
exec editInfo_User	10, 'MacGyver', 'Mascherano', 1, '01-01-1997', 'Gol contra também é gol!!'
UPDATE usuarios SET imagem = '/img/img-feed/masc.png' WHERE 10 = pessoa_id
exec cadUser		'Alisson', 'akhe@akhe', 'asdasd', 'Akhenathon', '01-01-1990'
UPDATE usuarios SET imagem = '/img/img-feed/akhe.png' WHERE 11 = pessoa_id
exec cadUser		'Dakela', '14k@14k', 'asdasd', 'DidUSayRazer?', '01-01-2000'
exec editInfo_User	12, 'Dakela', 'DidUSayRazer?', 1, '01-01-2000', 'Você disse Razer? Overwatch?'
UPDATE usuarios SET imagem = '/img/img-feed/14k.png' WHERE 12 = pessoa_id

exec cadGrupo	'CSGO Brasil', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', '/img/imgjogo/csgo.png', 1, 5
exec cadGrupo	'DOTO 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', '/img/imgjogo/dota2.png', 2, 5
exec cadGrupo	'Tomates Peladeiros', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', '/img/imgjogo/fifa17.png', 3, 5
exec cadGrupo	'Heartstone Zé Menino', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', '/img/imgjogo/heart.png', 4, 5
exec cadGrupo	'HOTS BR', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', '/img/imgjogo/hots.png', 5, 5
exec cadGrupo	'League of Chaos', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', '/img/imgjogo/lol.png', 6, 5
exec cadGrupo	'Paladins is da Best', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', '/img/imgjogo/overwatch.png', 7, 5

exec partGrupo	1, 6 exec partGrupo	1, 7 exec partGrupo	1, 8 exec partGrupo	1, 9 exec partGrupo	1, 10 exec partGrupo 1, 11 exec partGrupo 1, 12
exec partGrupo	2, 6 exec partGrupo	2, 7 exec partGrupo	2, 8 exec partGrupo	2, 9 exec partGrupo	2, 10 exec partGrupo 2, 11 exec partGrupo 2, 12
exec partGrupo	3, 6 exec partGrupo	3, 7 exec partGrupo	3, 8 exec partGrupo	3, 9 exec partGrupo	3, 10 exec partGrupo 3, 11 exec partGrupo 3, 12
exec partGrupo	4, 6 exec partGrupo	4, 7 exec partGrupo	4, 8 exec partGrupo	4, 9 exec partGrupo	4, 10 exec partGrupo 4, 11 exec partGrupo 4, 12
exec partGrupo	5, 6 exec partGrupo	5, 7 exec partGrupo	5, 8 exec partGrupo	5, 9 exec partGrupo	5, 10 exec partGrupo 5, 11 exec partGrupo 5, 12
exec partGrupo	6, 6 exec partGrupo	6, 7 exec partGrupo	6, 8 exec partGrupo	6, 9 exec partGrupo	6, 10 exec partGrupo 6, 11 exec partGrupo 6, 12
exec partGrupo	7, 6 exec partGrupo	7, 7 exec partGrupo	7, 8 exec partGrupo	7, 9 exec partGrupo	7, 10 exec partGrupo 7, 11 exec partGrupo 7, 12

exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5, 1
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6, 1
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7, 1
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 8, 1
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 9, 1
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 10, 1
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 11, 1
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 12, 1

exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5, 2
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6, 2
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7, 2
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 8, 2
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 9, 2
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 10, 2
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 11, 2
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 12, 2

exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5, 3
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6, 3
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7, 3
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 8, 3
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 9, 3
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 10, 3
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 11, 3
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 12, 3

exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5, 4
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6, 4
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7, 4
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 8, 4
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 9, 4
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 10, 4
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 11, 4
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 12, 4

exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5, 5
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6, 5
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7, 5
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 8, 5
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 9, 5
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 10, 5
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 11, 5
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 12, 5

exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5, 6
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6, 6
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7, 6
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 8, 6
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 9, 6
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 10, 6
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 11, 6
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 12, 6

exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5, 7
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6, 7
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7, 7
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 8, 7
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 9, 7
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 10, 7
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 11, 7
exec cadMsg		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 12, 7

exec cadEvento	'1º InterClasse da FatecRP', '2017-07-01', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'2º InterClasse da FatecRP', '2017-07-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'3º InterClasse da FatecRP', '2017-07-15', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'4º InterClasse da FatecRP', '2017-07-21', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'5º InterClasse da FatecRP', '2017-07-28', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'6º InterClasse da FatecRP', '2017-08-05', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'7º InterClasse da FatecRP', '2017-09-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'8º InterClasse da FatecRP', '2017-10-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'9º InterClasse da FatecRP', '2017-11-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'10º InterClasse da FatecRP', '2017-12-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'11º InterClasse da FatecRP', '2018-01-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1
exec cadEvento	'12º InterClasse da FatecRP', '2018-02-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 1

exec cadEvento	'1º InterClasse da FatecRP', '2017-07-01', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'2º InterClasse da FatecRP', '2017-07-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'3º InterClasse da FatecRP', '2017-07-15', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'4º InterClasse da FatecRP', '2017-07-21', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'5º InterClasse da FatecRP', '2017-07-28', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'6º InterClasse da FatecRP', '2017-08-05', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'7º InterClasse da FatecRP', '2017-09-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'8º InterClasse da FatecRP', '2017-10-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'9º InterClasse da FatecRP', '2017-11-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'10º InterClasse da FatecRP', '2017-12-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'11º InterClasse da FatecRP', '2018-01-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2
exec cadEvento	'12º InterClasse da FatecRP', '2018-02-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 2

exec cadEvento	'1º InterClasse da FatecRP', '2017-07-01', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'2º InterClasse da FatecRP', '2017-07-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'3º InterClasse da FatecRP', '2017-07-15', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'4º InterClasse da FatecRP', '2017-07-21', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'5º InterClasse da FatecRP', '2017-07-28', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'6º InterClasse da FatecRP', '2017-08-05', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'7º InterClasse da FatecRP', '2017-09-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'8º InterClasse da FatecRP', '2017-10-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'9º InterClasse da FatecRP', '2017-11-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'10º InterClasse da FatecRP', '2017-12-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'11º InterClasse da FatecRP', '2018-01-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3
exec cadEvento	'12º InterClasse da FatecRP', '2018-02-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 3

exec cadEvento	'1º InterClasse da FatecRP', '2017-07-01', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'2º InterClasse da FatecRP', '2017-07-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'3º InterClasse da FatecRP', '2017-07-15', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'4º InterClasse da FatecRP', '2017-07-21', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'5º InterClasse da FatecRP', '2017-07-28', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'6º InterClasse da FatecRP', '2017-08-05', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'7º InterClasse da FatecRP', '2017-09-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'8º InterClasse da FatecRP', '2017-10-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'9º InterClasse da FatecRP', '2017-11-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'10º InterClasse da FatecRP', '2017-12-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'11º InterClasse da FatecRP', '2018-01-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4
exec cadEvento	'12º InterClasse da FatecRP', '2018-02-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 4

exec cadEvento	'1º InterClasse da FatecRP', '2017-07-01', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'2º InterClasse da FatecRP', '2017-07-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'3º InterClasse da FatecRP', '2017-07-15', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'4º InterClasse da FatecRP', '2017-07-21', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'5º InterClasse da FatecRP', '2017-07-28', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'6º InterClasse da FatecRP', '2017-08-05', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'7º InterClasse da FatecRP', '2017-09-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'8º InterClasse da FatecRP', '2017-10-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'9º InterClasse da FatecRP', '2017-11-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'10º InterClasse da FatecRP', '2017-12-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'11º InterClasse da FatecRP', '2018-01-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5
exec cadEvento	'12º InterClasse da FatecRP', '2018-02-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 5

exec cadEvento	'1º InterClasse da FatecRP', '2017-07-01', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'2º InterClasse da FatecRP', '2017-07-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'3º InterClasse da FatecRP', '2017-07-15', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'4º InterClasse da FatecRP', '2017-07-21', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'5º InterClasse da FatecRP', '2017-07-28', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'6º InterClasse da FatecRP', '2017-08-05', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'7º InterClasse da FatecRP', '2017-09-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'8º InterClasse da FatecRP', '2017-10-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'9º InterClasse da FatecRP', '2017-11-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'10º InterClasse da FatecRP', '2017-12-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'11º InterClasse da FatecRP', '2018-01-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6
exec cadEvento	'12º InterClasse da FatecRP', '2018-02-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 6

exec cadEvento	'1º InterClasse da FatecRP', '2017-07-01', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'2º InterClasse da FatecRP', '2017-07-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'3º InterClasse da FatecRP', '2017-07-15', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'4º InterClasse da FatecRP', '2017-07-21', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'5º InterClasse da FatecRP', '2017-07-28', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'6º InterClasse da FatecRP', '2017-08-05', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'7º InterClasse da FatecRP', '2017-09-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'8º InterClasse da FatecRP', '2017-10-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'9º InterClasse da FatecRP', '2017-11-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'10º InterClasse da FatecRP', '2017-12-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'11º InterClasse da FatecRP', '2018-01-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7
exec cadEvento	'12º InterClasse da FatecRP', '2018-02-08', '20:30:00.0000000', 1, null, null, null, null, null, null, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vitae odio quis nunc volutpat interdum eleifend id ante. Nam suscipit suscipit placerat. Donec eget mauris vitae mi mattis sodales ac ac quam. Donec dictum fringilla sapien, id maximus nisl. Nulla mollis congue erat vel auctor. Vivamus sed vehicula erat, quis.', 7

exec partEvento 1, 6, 1 exec partEvento 1, 7, 1 exec partEvento 1, 8, 1 exec partEvento 1, 9, 1 exec partEvento 1, 10, 1 exec partEvento 1, 11, 1 exec partEvento 1, 12, 1
exec partEvento 1, 6, 2 exec partEvento 1, 7, 2 exec partEvento 1, 8, 2 exec partEvento 1, 9, 2 exec partEvento 1, 10, 2 exec partEvento 1, 11, 2 exec partEvento 1, 12, 2
exec partEvento 1, 6, 3 exec partEvento 1, 7, 3 exec partEvento 1, 8, 3 exec partEvento 1, 9, 3 exec partEvento 1, 10, 3 exec partEvento 1, 11, 3 exec partEvento 1, 12, 3
exec partEvento 1, 6, 4 exec partEvento 1, 7, 4 exec partEvento 1, 8, 4 exec partEvento 1, 9, 4 exec partEvento 1, 10, 4 exec partEvento 1, 11, 4 exec partEvento 1, 12, 4
exec partEvento 1, 6, 5 exec partEvento 1, 7, 5 exec partEvento 1, 8, 5 exec partEvento 1, 9, 5 exec partEvento 1, 10, 5 exec partEvento 1, 11, 5 exec partEvento 1, 12, 5
exec partEvento 1, 6, 6 exec partEvento 1, 7, 6 exec partEvento 1, 8, 6 exec partEvento 1, 9, 6 exec partEvento 1, 10, 6 exec partEvento 1, 11, 6 exec partEvento 1, 12, 6
exec partEvento 1, 6, 7 exec partEvento 1, 7, 7 exec partEvento 1, 8, 7 exec partEvento 1, 9, 7 exec partEvento 1, 10, 7 exec partEvento 1, 11, 7 exec partEvento 1, 12, 7
exec partEvento 1, 6, 8 exec partEvento 1, 7, 8 exec partEvento 1, 8, 8 exec partEvento 1, 9, 8 exec partEvento 1, 10, 8 exec partEvento 1, 11, 8 exec partEvento 1, 12, 8
exec partEvento 1, 6, 9 exec partEvento 1, 7, 9 exec partEvento 1, 8, 9 exec partEvento 1, 9, 9 exec partEvento 1, 10, 9 exec partEvento 1, 11, 9 exec partEvento 1, 12, 9
exec partEvento 1, 6, 10 exec partEvento 1, 7, 10 exec partEvento 1, 8, 10 exec partEvento 1, 9, 10 exec partEvento 1, 10, 10 exec partEvento 1, 11, 10 exec partEvento 1, 12, 10
exec partEvento 1, 6, 11 exec partEvento 1, 7, 11 exec partEvento 1, 8, 11 exec partEvento 1, 9, 11 exec partEvento 1, 10, 11 exec partEvento 1, 11, 11 exec partEvento 1, 12, 11
exec partEvento 1, 6, 12 exec partEvento 1, 7, 12 exec partEvento 1, 8, 12 exec partEvento 1, 9, 12 exec partEvento 1, 10, 12 exec partEvento 1, 11, 12 exec partEvento 1, 12, 12


